name: generator
on:
  schedule:
    - cron:  '0 4 * * *'
  repository_dispatch:
    types: [generate]
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install
      - run: npm run submit-prs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
